const collections = [
  {
    title: "Best Selling",
    slug: "best-selling",
    image: "/images/collections/collection1.PNG",
  },
  {
    title: "Collection name 2",
    slug: "collection-name-2",
    image: "/images/collections/collection2.PNG",
  },
  {
    title: "Collection name 3",
    slug: "collection-name-3",
    image: "/images/collections/collection3.PNG",
  },
  {
    title: "Collection name 4",
    slug: "collection-name-4",
    image: "/images/collections/collection4.PNG",
  },
  {
    title: "Collection name 5",
    slug: "collection-name-5",
    image: "/images/collections/collection5.PNG",
  },
  {
    title: "Collection name 6",
    slug: "collection-name-6",
    image: "/images/collections/collection6.PNG",
  },
  {
    title: "Collection name 7",
    slug: "collection-name-7",
    image: "/images/collections/collection1.PNG",
  },
  {
    title: "Collection name 8",
    slug: "collection-name-8",
    image: "/images/collections/collection2.PNG",
  },
  {
    title: "Collection name 9",
    slug: "collection-name-9",
    image: "/images/collections/collection3.PNG",
  },
];

const products = [
  {
    price: 200,
    image: "/images/products/product-test.PNG",
    availability: true,
    name: "Product example 1",
    slug: "product-example-1",
    size: ["XL", "XS", "L", "M", "S"],
    colors: [
      { name: "light grey", hex: "#ddd" },
      { name: "green", hex: "#ace1af" },
      { name: "red", hex: "#fd5c63" },
    ],
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    images: [
      "/images/products/product-test.PNG",
      "/images/products/product-test1.PNG",
      "/images/products/product-test2.PNG",
      "/images/products/product-test3.PNG",
    ],
  },
  {
    price: 200,
    image: "/images/products/product-test1.PNG",
    availability: true,
    name: "Product example 2",
    slug: "product-example-2",
    colors: [
      { name: "light grey", hex: "#ddd" },
      { name: "dark brown", hex: "#222" },
      { name: "brown", hex: "#333" },
    ],
    size: ["XL", "XS", "L", "M", "S"],
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    images: [
      "/images/products/product-test.PNG",
      "/images/products/product-test1.PNG",
      "/images/products/product-test2.PNG",
      "/images/products/product-test3.PNG",
    ],
  },
  {
    price: 200,
    image: "/images/products/product-test2.PNG",
    name: "Product example 3",
    slug: "product-example-3",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    availability: true,
    size: ["XL", "XS", "L", "M", "S"],
    colors: [
      { name: "light grey", hex: "#ddd" },
      { name: "green", hex: "#ace1af" },
      { name: "brown", hex: "#333" },
    ],
    images: [
      "/images/products/product-test.PNG",
      "/images/products/product-test1.PNG",
      "/images/products/product-test2.PNG",
      "/images/products/product-test3.PNG",
    ],
  },
  {
    price: 200,
    image: "/images/products/product-test3.PNG",
    availability: true,
    name: "Product example 4",
    slug: "product-example-4",
    size: ["XL", "XS", "L", "M", "S"],
    colors: [
      { name: "red", hex: "#fd5c63" },
      { name: "green", hex: "#ace1af" },
      { name: "dark brown", hex: "#222" },
    ],
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    images: [
      "/images/products/product-test.PNG",
      "/images/products/product-test1.PNG",
      "/images/products/product-test2.PNG",
      "/images/products/product-test3.PNG",
    ],
  },
  {
    price: 200,
    image: "/images/products/product-test.PNG",
    availability: true,
    name: "Product example 5",
    slug: "product-example-5",
    size: ["XL", "XS", "L", "M", "S"],
    colors: [
      { name: "red", hex: "#fd5c63" },
      { name: "light grey", hex: "#ddd" },
      { name: "dark brown", hex: "#222" },
    ],
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    images: [
      "/images/products/product-test.PNG",
      "/images/products/product-test1.PNG",
      "/images/products/product-test2.PNG",
      "/images/products/product-test3.PNG",
    ],
  },
  {
    price: 200,
    image: "/images/products/product-test1.PNG",
    availability: true,
    name: "Product example 6",
    slug: "product-example-6",
    size: ["XL", "XS", "L", "M", "S"],
    colors: [
      { name: "red", hex: "#fd5c63" },
      { name: "green", hex: "#ace1af" },
      { name: "dark brown", hex: "#222" },
    ],
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    images: [
      "/images/products/product-test.PNG",
      "/images/products/product-test1.PNG",
      "/images/products/product-test2.PNG",
      "/images/products/product-test3.PNG",
    ],
  },
  {
    price: 200,
    image: "/images/products/product-test2.PNG",
    availability: true,
    name: "Product example 7",
    slug: "product-example-7",
    size: ["XL", "XS", "L", "M", "S"],
    colors: [
      { name: "red", hex: "#fd5c63" },
      { name: "light grey", hex: "#ddd" },
      { name: "dark brown", hex: "#222" },
    ],
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    images: [
      "/images/products/product-test.PNG",
      "/images/products/product-test1.PNG",
      "/images/products/product-test2.PNG",
      "/images/products/product-test3.PNG",
    ],
  },
  {
    price: 200,
    image: "/images/products/product-test3.PNG",
    availability: false,
    name: "Product example 8",
    slug: "product-example-8",
    size: ["XL", "XS", "L", "M", "S"],
    colors: [
      { name: "red", hex: "#fd5c63" },
      { name: "green", hex: "#ace1af" },
      { name: "dark brown", hex: "#222" },
    ],
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    images: [
      "/images/products/product-test.PNG",
      "/images/products/product-test1.PNG",
      "/images/products/product-test2.PNG",
      "/images/products/product-test3.PNG",
    ],
  },
  {
    price: 200,
    image: "/images/products/product-test.PNG",
    availability: true,
    name: "Product example 9",
    slug: "product-example-9",
    size: ["XL", "XS", "L", "M", "S"],
    colors: [
      { name: "light grey", hex: "#ddd" },
      { name: "green", hex: "#ace1af" },
      { name: "brown", hex: "#333" },
    ],
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    images: [
      "/images/products/product-test.PNG",
      "/images/products/product-test1.PNG",
      "/images/products/product-test2.PNG",
      "/images/products/product-test3.PNG",
    ],
  },
  {
    price: 200,
    image: "/images/products/product-test1.PNG",
    availability: false,
    name: "Product example 10",
    slug: "product-example-10",
    size: ["XL", "XS", "L", "M", "S"],
    colors: [
      { name: "light grey", hex: "#ddd" },
      { name: "red", hex: "#fd5c63" },
      { name: "dark brown", hex: "#222" },
    ],
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    images: [
      "/images/products/product-test.PNG",
      "/images/products/product-test1.PNG",
      "/images/products/product-test2.PNG",
      "/images/products/product-test3.PNG",
    ],
  },
];

export { collections, products };
